data:
  train_files: hiyouga/math12k@train
  val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  video_key: videos
  video_fps: 2.0
  max_prompt_length: 2048
  max_response_length: 2048
  train_batch_size: 8
  val_batch_size: 128
  format_prompt: ./examples/format_prompt/math.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: false

algorithm:
  adv_estimator: grpo
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

actor:
  ppo_mini_batch_size: 8  # equivalent to verl's actor.ppo_mini_batch_size
  ppo_micro_batch_size_per_gpu: 1  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
  log_prob_micro_batch_size_per_gpu: 2  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
  max_grad_norm: 1.0
  padding_free: true
  dynamic_batching: true
  ulysses_size: 1
  model:
    model_path: Qwen/Qwen2-VL-2B-Instruct
    enable_gradient_checkpointing: true
    trust_remote_code: true  # Qwen2-VL需要设为true
    freeze_vision_tower: false
  optim:
    lr: 1.0e-6
    weight_decay: 1.0e-2
    strategy: adamw  # {adamw, adamw_bf16}
    lr_warmup_ratio: 0.0
  fsdp:
    enable_full_shard: true
    enable_cpu_offload: true
    use_orig_params: true
    offload_params: true  # true: more CPU memory; false: more GPU memory
    offload_optimizer: true  # true: more CPU memory; false: more GPU memory
rollout:
  n: 3
  temperature: 1.0
  top_p: 1.0
  limit_images: 0
  tensor_parallel_size: 1
  disable_tqdm: false
  vllm:
    gpu_memory_utilization: 0.4
    enforce_eager: true
    enable_chunked_prefill: false
  val_override_config:
    temperature: 0.0
    top_p: 1.0
    top_k: -1
    n: 1
critic: null
ref:
  fsdp:
    enable_full_shard: true
    enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
    offload_params: false
reward:
  reward_type: batch
  reward_function: ./examples/reward_function/math.py:compute_score
  skip_special_tokens: false
trainer:
  total_epochs: 1
  max_steps: null
  project_name: rlava
  experiment_name: qwen2_5_7b_math_grpo
  logger: ["console", "tensorboard"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20  # -1 means no limit
  val_freq: -1  # -1 to disable
  val_before_train: false
  val_only: false
  val_generations_to_log: 3
  save_freq: 100  # -1 to disable
  save_limit: 3  # -1 to disable
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
